spring:
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  thymeleaf:
    cache: false
    check-template: true
    check-template-location: true
    enabled: true
    encoding: UTF-8
    # excluded-view-names:
    # mode: HTML5
    prefix: classpath:/templates/
    suffix: .html
    # template-resolver-order:
    # view-names:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password: sa
  #    http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
  #logging color
  output:
    ansi:
      enabled: ALWAYS


logging:
  level:
    org:
      hibernate:TRACE

filepath: /images/products/

